"""add_auction_delivery_fields

Revision ID: 04276d30f514
Revises: bb265bd26855
Create Date: 2026-06-18 09:28:35.977966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04276d30f514'
down_revision: Union[str, None] = 'bb265bd26855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auctions', sa.Column('delivery_code', sa.String(length=10), nullable=True))
    op.add_column('auctions', sa.Column('delivery_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('auctions', sa.Column('delivery_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_auctions_delivery_code'), 'auctions', ['delivery_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auctions_delivery_code'), table_name='auctions')
    op.drop_column('auctions', 'delivery_confirmed_at')
    op.drop_column('auctions', 'delivery_status')
    op.drop_column('auctions', 'delivery_code')
    # ### end Alembic commands ###
