"""add_escrow_delivery_code

Revision ID: 22f76ac06025
Revises: 5e8f3a2c4b1d
Create Date: 2026-06-17 18:56:40.180989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22f76ac06025'
down_revision: Union[str, None] = '5e8f3a2c4b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raffle_id', sa.UUID(), nullable=False),
    sa.Column('winner_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('qr_data', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('escrow_amount_centavos', sa.BigInteger(), nullable=False),
    sa.Column('dual_confirmation', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by_winner_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by_creator_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispute_reason', sa.Text(), nullable=True),
    sa.Column('dispute_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispute_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispute_resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raffle_id'], ['raffles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_codes_code'), 'delivery_codes', ['code'], unique=True)
    op.create_index(op.f('ix_delivery_codes_raffle_id'), 'delivery_codes', ['raffle_id'], unique=True)
    op.create_table('delivery_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_code_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delivery_code_id'], ['delivery_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_audit_logs_delivery_code_id'), 'delivery_audit_logs', ['delivery_code_id'], unique=False)
    op.drop_constraint('raffle_tickets_user_id_fkey', 'raffle_tickets', type_='foreignkey')
    op.create_foreign_key(None, 'raffle_tickets', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('raffles', sa.Column('pool_held_centavos', sa.BigInteger(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raffles', 'pool_held_centavos')
    op.drop_constraint(None, 'raffle_tickets', type_='foreignkey')
    op.create_foreign_key('raffle_tickets_user_id_fkey', 'raffle_tickets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_delivery_audit_logs_delivery_code_id'), table_name='delivery_audit_logs')
    op.drop_table('delivery_audit_logs')
    op.drop_index(op.f('ix_delivery_codes_raffle_id'), table_name='delivery_codes')
    op.drop_index(op.f('ix_delivery_codes_code'), table_name='delivery_codes')
    op.drop_table('delivery_codes')
    # ### end Alembic commands ###
