"""add_auction_starts_at

Revision ID: 28d43cb8f7f2
Revises: 04276d30f514
Create Date: 2026-06-18 10:11:23.252164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28d43cb8f7f2'
down_revision: Union[str, None] = '04276d30f514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('auctions', sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE auctions SET starts_at = ends_at WHERE starts_at IS NULL")
    op.alter_column('auctions', 'starts_at', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auctions', 'starts_at')
    # ### end Alembic commands ###
