"""add bisno model

Revision ID: 69b2b88f8720
Revises: 2a4f8c1d9e3b
Create Date: 2026-06-17 16:59:56.514590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b2b88f8720'
down_revision: Union[str, None] = '2a4f8c1d9e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bisnos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PRODUCT', 'SERVICE', name='bisnotype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('TECNOLOGIA', 'ENTREGAS', 'TRANSPORTE', 'SERVICOS', 'MODA', 'CASA', 'EDUCACAO', 'SAUDE', 'OUTRO', name='bisnocategory'), nullable=False),
    sa.Column('contact_method', sa.Enum('CHAT', 'WHATSAPP', 'CALL', name='contactmethod'), nullable=False),
    sa.Column('contact_value', sa.String(length=100), nullable=True),
    sa.Column('location_name', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('price_centavos', sa.Integer(), nullable=True),
    sa.Column('negotiable', sa.Boolean(), nullable=False),
    sa.Column('condition', sa.Enum('NEW', 'USED', name='productcondition'), nullable=True),
    sa.Column('price_type', sa.Enum('HOURLY', 'FIXED', 'NEGOTIABLE', name='pricetype'), nullable=True),
    sa.Column('service_modality', sa.Enum('HOME', 'IN_PERSON', name='servicemodality'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SOLD', 'COMPLETED', 'CANCELLED', name='bisnostatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bisnos_created_at'), 'bisnos', ['created_at'], unique=False)
    op.create_index(op.f('ix_bisnos_creator_id'), 'bisnos', ['creator_id'], unique=False)
    op.create_index(op.f('ix_bisnos_status'), 'bisnos', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bisnos_status'), table_name='bisnos')
    op.drop_index(op.f('ix_bisnos_creator_id'), table_name='bisnos')
    op.drop_index(op.f('ix_bisnos_created_at'), table_name='bisnos')
    op.drop_table('bisnos')
    # ### end Alembic commands ###
