"""add_auction_escrow_anti_sniping_audit

Revision ID: bb265bd26855
Revises: 22f76ac06025
Create Date: 2026-06-18 09:26:21.083944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb265bd26855'
down_revision: Union[str, None] = '22f76ac06025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auction_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_audit_logs_auction_id'), 'auction_audit_logs', ['auction_id'], unique=False)
    op.add_column('auctions', sa.Column('pool_held_centavos', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('auctions', sa.Column('ends_at_extended', sa.DateTime(timezone=True), nullable=True))
    op.add_column('auctions', sa.Column('anti_sniping_window_seconds', sa.Integer(), server_default='120', nullable=False))
    op.add_column('auctions', sa.Column('extensions_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('auctions', sa.Column('max_extensions', sa.Integer(), server_default='5', nullable=False))
    op.add_column('bids', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('bids', sa.Column('refunded', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bids', 'refunded')
    op.drop_column('bids', 'is_active')
    op.drop_column('auctions', 'max_extensions')
    op.drop_column('auctions', 'extensions_count')
    op.drop_column('auctions', 'anti_sniping_window_seconds')
    op.drop_column('auctions', 'ends_at_extended')
    op.drop_column('auctions', 'pool_held_centavos')
    op.drop_index(op.f('ix_auction_audit_logs_auction_id'), table_name='auction_audit_logs')
    op.drop_table('auction_audit_logs')
    # ### end Alembic commands ###
